sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer

language: java
#dist: trusty
jdk:
  - oraclejdk8

install: mvn -B -e install -U -DskipTests=true

script: mvn -B -e verify -U -Dmaven.javadoc.skip=true -Dmaven.groovydoc.skip=true

after_success:

cache:
  directories:
  - $HOME/.m2

env:
  global:

branches:
  only:
    - master
    - /^release.*$/
